[tool.poetry]
name = "DynamicAdaptor"
version = "0.1.1"
description = ""
authors = ["DMC <lzxder@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = false
secondary = false

