[tool.poetry]
name = "DynamicAdaptor"
version = "0.3.7"
description = ""
authors = ["DMC <lzxder@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.0"
pydantic = "^1.10.4"
loguru = "^0.6.0"


[tool.poetry.group.dev.dependencies]
bilirpc = "^0.1.3"
httpx = "^0.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = false
secondary = false

